version: '3'
services:
  backend:
    image: backend
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    build:
      context: backend
      args:
        - DOCKER_BUILDKIT=1
      dockerfile: Dockerfile
    ports:
      - 8000:80
  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - 80:80