name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v3
    - name: create credentials file
      run:
        echo '${{ secrets.CLOUD_CREDS }}' > cloud_credentials.json
    - name: Docker Compose
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      run: docker compose up -d --force-recreate --build